# Recommended config: 0.01 timestep, 120 fps

# 0.001 ; 0.01 ; 0.16
timestep: 0.010

# 60 ; 120 ; 144
fps: 120

# true ; false
trajectory: true

# true ; false
true_form: false

# true ; false
auto_shift: true

# 1 ; 3 ; 5
# 1: longitudinal point-mass
# 3: powertrain engine curve and gearing
# 5: traction curve and slip ratio
longitudinal_engine: 5

# true ; false
inverse_steering: true

# runtime options:
kb_throttle_ramp_engage: 0.5
kb_throttle_ramp_release: 0.2

kb_brake_ramp_engage: 0.5
kb_brake_ramp_release: 0.2

kb_steer_ramp_engage: 0.5
kb_steer_ramp_release: 0.1

# constants preset (most are adapted to use Longitudinal Engine 5):
# "DEFAULT"
# "ECONOMY_COMPACT"
# "SPORTS_CAR"
# "TURBO_PERFORMANCE"
# "SUV_TRUCK"
# "ELECTRIC_EV"
# "GO_KART"
# "LIMOUSINE"
# "MCLAREN_P1" (roughly estimated from public sources, very different from the others
# McLaren P1 is added to validate a mathematical modeling paper of mine)
preset: "DEFAULT"